name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        build_type: [Release, Debug]
        compiler: [{
          "cc": "gcc",
          "cxx": "g++"
         }, {
          "cc": "clang",
          "cxx": "clang++"
        }]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        libboost-dev \
        libgtest-dev \
        libyaml-cpp-dev

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
        -DBUILD_TESTING=ON

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: make -j2

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: make test

  testcov:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        lcov \
        libboost-dev \
        libgtest-dev \
        libyaml-cpp-dev

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build \
        -DCMAKE_BUILD_TYPE=Debug \
        -DBUILD_TESTING=ON \
        -DCMAKE_CXX_FLAGS="-O0 -g --coverage -fno-inline" \
        -DCMAKE_EXE_LINKER_FLAGS="--coverage"

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: make -j2

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: make test

    - name: Analyze coverage
      working-directory: ${{ github.workspace }}
      run: |
        lcov -c --no-external --directory include -d build/CMakeFiles -o coverage.info
        lcov --list coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info

